version: '3'
services:
  # php-cli:
  #  build: ./php
  #  volumes:
  #    - ./web:/var/www/html
  #  working_dir: /var/www/html
  db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: kinyujoshi_development
      MYSQL_ROOT_PASSWORD: pass
      TZ: "Asia/Tokyo"
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql
  test-db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: kinyujoshi_test
      MYSQL_ROOT_PASSWORD: pass
      TZ: "Asia/Tokyo"
    ports:
      - '3308:3306'
    volumes:
      - test-db-data:/var/lib/mysql
  web:
    build: ./php
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/html
      - ./config/apache2/sites-available:/etc/apache2/sites-available
    working_dir: /var/www/html
    environment:
      FUEL_ENV: development
    depends_on:
      - db
      - smtp
#      - test-db
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - TZ=Asia/Tokyo
  composer:
    image: composer/composer:php5
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ~/.composer/auth.json:/root/composer/auth.json
      - ./web:/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=pass
    links:
      - db
    ports:
       - 8080:80
    volumes:
       - /sessions

  minio:
    image: minio/minio
    volumes:
      - s3-data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data 

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/sunday-lunch;
      /usr/bin/mc policy public myminio/sunday-lunch;
      exit 0;
      "

volumes:
  db-data:
    driver: local
  s3-data:
    driver: local
  test-db-data:
    driver: local
