version: '3'
services:
#  php-cli:
#    build: ./php
#    volumes:
#      - ./web:/var/www/html
#      - ./php/php.ini:/usr/local/etc/php/php.ini
#    working_dir: /var/www/html
  db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: kinyujoshi_development
      MYSQL_ROOT_PASSWORD: pass
      TZ: "Asia/Tokyo"
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql
  test-db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: kinyujoshi_test
      MYSQL_ROOT_PASSWORD: pass
      TZ: "Asia/Tokyo"
    ports:
      - '3308:3306'
    volumes:
      - test-db-data:/var/lib/mysql
  web:
    build: ./php
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/html
      - ./config/apache2/sites-available:/etc/apache2/sites-available
    working_dir: /var/www/html
    depends_on:
      - db
#      - test-db
  composer:
    image: composer/composer:php5
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ~/.composer/auth.json:/root/composer/auth.json
      - ./web:/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app

volumes:
  db-data:
    driver: local
  test-db-data:
    driver: local
