version: '3'
services:
  db:
    build: ./mysql
    environment:
      - MYSQL_DATABASE=kinyujoshi_development
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql

  web:
    build: ./php
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/html
      - ./config/apache2/sites-available:/etc/apache2/sites-available
    working_dir: /var/www/html
    environment:
      FUEL_ENV: development
    depends_on:
      - db
      - smtp

#  chat:
#    build: ./chat
#    environment:
#      - TZ=Asia/Tokyo
#      - DB_HOST=db
#      - DB_NAME=kinyujoshi_development
#      - DB_USER=root
#      - DB_PASSWORD=pass
#      - COOKIE_DOMAIN=localhost
#    ports:
#      - '8080:80'
#    volumes:
#      - ./chat/app:/var/www/html
#    working_dir: /var/www/html
#    command: php bin/chat-server.php
#    depends_on:
#      - db

  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - TZ=Asia/Tokyo
  composer:
    image: composer:1.9.3
    environment:
      TZ: "Asia/Tokyo"
    volumes:
#      - ~/.composer/auth.json:/root/composer/auth.json
      - ./web:/app
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=db
#      - PMA_USER=root
#      - PMA_PASSWORD=pass
#    links:
#      - db
#    ports:
#       - 8888:80
#    volumes:
#       - /sessions

  oil:
    build: ./php
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./web:/var/www/html
    working_dir: /var/www/html
    environment:
      FUEL_ENV: development
    entrypoint:
      - php
      - oil
    depends_on:
      - db
      - smtp


  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    entrypoint: sh
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      cp -r /export/* /data/;
      /opt/bin/minio server /data --console-address :9001;"
    volumes:
      - s3-data:/data
      - ./minio/export:/export
      - ./minio/policies:/policies

volumes:
  db-data:
    driver: local
  s3-data:
    driver: local
