version: '3'
services:
  db:
    build: ./mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: kinyujoshi
      MYSQL_ROOT_PASSWORD: pass
  #  volumes:
  #    - db:/var/lib/mysql
  web:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/html
      - ./config/apache2/sites-available:/etc/apache2/sites-available
    depends_on:
      - db
  composer:
      image: composer/composer:php5
      volumes:
        - ~/.composer/auth.json:/root/composer/auth.json
        - ./web:/app
        - ./php/php.ini:/usr/local/etc/php/php.ini
      working_dir: /app
# volumes:
#   db:
