<?php

$seeds = array(
    array('id' => '1', 'code' => 'PqmWc4', 'name' => '北海道', 'created_at' => \DB::expr('now()')),
    array('id' => '2', 'code' => '1gjzQK', 'name' => '青森県', 'created_at' => \DB::expr('now()')),
    array('id' => '3', 'code' => '96MGze', 'name' => '岩手県', 'created_at' => \DB::expr('now()')),
    array('id' => '4', 'code' => '1MQjDx', 'name' => '宮城県', 'created_at' => \DB::expr('now()')),
    array('id' => '5', 'code' => '7tCUJs', 'name' => '秋田県', 'created_at' => \DB::expr('now()')),
    array('id' => '6', 'code' => 'Ouskl7', 'name' => '山形県', 'created_at' => \DB::expr('now()')),
    array('id' => '7', 'code' => 'UHgQxn', 'name' => '福島県', 'created_at' => \DB::expr('now()')),
    array('id' => '8', 'code' => 'gbT27a', 'name' => '茨城県', 'created_at' => \DB::expr('now()')),
    array('id' => '9', 'code' => 'Fh1Lcu', 'name' => '栃木県', 'created_at' => \DB::expr('now()')),
    array('id' => '10', 'code' => 't0NrAm', 'name' => '群馬県', 'created_at' => \DB::expr('now()')),
    array('id' => '11', 'code' => 'FO48ig', 'name' => '埼玉県', 'created_at' => \DB::expr('now()')),
    array('id' => '12', 'code' => '3yIZ9w', 'name' => '千葉県', 'created_at' => \DB::expr('now()')),
    array('id' => '13', 'code' => 'IZKtzK', 'name' => '東京都', 'created_at' => \DB::expr('now()')),
    array('id' => '14', 'code' => 'mK7bBj', 'name' => '神奈川県', 'created_at' => \DB::expr('now()')),
    array('id' => '15', 'code' => 'xKQR8z', 'name' => '新潟県', 'created_at' => \DB::expr('now()')),
    array('id' => '16', 'code' => 'a2q97o', 'name' => '富山県', 'created_at' => \DB::expr('now()')),
    array('id' => '17', 'code' => 'rhB7oN', 'name' => '石川県', 'created_at' => \DB::expr('now()')),
    array('id' => '18', 'code' => 'oFzkpj', 'name' => '福井県', 'created_at' => \DB::expr('now()')),
    array('id' => '19', 'code' => 'lBdEbx', 'name' => '山梨県', 'created_at' => \DB::expr('now()')),
    array('id' => '20', 'code' => 'ybFLGL', 'name' => '長野県', 'created_at' => \DB::expr('now()')),
    array('id' => '21', 'code' => 'lTLXGc', 'name' => '岐阜県', 'created_at' => \DB::expr('now()')),
    array('id' => '22', 'code' => 'ekAY14', 'name' => '静岡県', 'created_at' => \DB::expr('now()')),
    array('id' => '23', 'code' => 'UWhlF4', 'name' => '愛知県', 'created_at' => \DB::expr('now()')),
    array('id' => '24', 'code' => 'qlszGB', 'name' => '三重県', 'created_at' => \DB::expr('now()')),
    array('id' => '25', 'code' => '48tOoz', 'name' => '滋賀県', 'created_at' => \DB::expr('now()')),
    array('id' => '26', 'code' => 'RU1gnP', 'name' => '京都府', 'created_at' => \DB::expr('now()')),
    array('id' => '27', 'code' => '6th0yi', 'name' => '大阪府', 'created_at' => \DB::expr('now()')),
    array('id' => '28', 'code' => 'wO0MHH', 'name' => '兵庫県', 'created_at' => \DB::expr('now()')),
    array('id' => '29', 'code' => '2zkVbN', 'name' => '奈良県', 'created_at' => \DB::expr('now()')),
    array('id' => '30', 'code' => 's723Fo', 'name' => '和歌山県', 'created_at' => \DB::expr('now()')),
    array('id' => '31', 'code' => '5CZLvZ', 'name' => '鳥取県', 'created_at' => \DB::expr('now()')),
    array('id' => '32', 'code' => 'qXxp2W', 'name' => '島根県', 'created_at' => \DB::expr('now()')),
    array('id' => '33', 'code' => 'ctA8SI', 'name' => '岡山県', 'created_at' => \DB::expr('now()')),
    array('id' => '34', 'code' => 'xhpWvE', 'name' => '広島県', 'created_at' => \DB::expr('now()')),
    array('id' => '35', 'code' => '9UgdrM', 'name' => '山口県', 'created_at' => \DB::expr('now()')),
    array('id' => '36', 'code' => 'p0a5m9', 'name' => '徳島県', 'created_at' => \DB::expr('now()')),
    array('id' => '37', 'code' => '8qODBs', 'name' => '香川県', 'created_at' => \DB::expr('now()')),
    array('id' => '38', 'code' => 'xaGowj', 'name' => '愛媛県', 'created_at' => \DB::expr('now()')),
    array('id' => '39', 'code' => 'SXsbsf', 'name' => '高知県', 'created_at' => \DB::expr('now()')),
    array('id' => '40', 'code' => 'ULWQWj', 'name' => '福岡県', 'created_at' => \DB::expr('now()')),
    array('id' => '41', 'code' => 'F38ibL', 'name' => '佐賀県', 'created_at' => \DB::expr('now()')),
    array('id' => '42', 'code' => 'RD5yG4', 'name' => '長崎県', 'created_at' => \DB::expr('now()')),
    array('id' => '43', 'code' => 'AxVu7Q', 'name' => '熊本県', 'created_at' => \DB::expr('now()')),
    array('id' => '44', 'code' => 't6Oc7x', 'name' => '大分県', 'created_at' => \DB::expr('now()')),
    array('id' => '45', 'code' => 'RWf7Ia', 'name' => '宮崎県', 'created_at' => \DB::expr('now()')),
    array('id' => '46', 'code' => 'TOdXmS', 'name' => '鹿児島県', 'created_at' => \DB::expr('now()')),
    array('id' => '47', 'code' => 'tCOZcd', 'name' => '沖縄県', 'created_at' => \DB::expr('now()')),
);

foreach ($seeds as $key => $seed) {
    \DB::delete('prefectures')->where(array('id' => $seed['id']))->execute();
    \DB::insert('prefectures')->set($seed)->execute();
}
