<?php
return array(
  'version' => 
  array(
    'app' => 
    array(
      'default' => 
      array(
        0 => '001_create_users',
        1 => '002_create_mybbs',
        2 => '003_create_addresses',
        3 => '005_create_applications',
        4 => '006_create_blogs',
        5 => '007_create_categories',
        6 => '008_create_comment',
        7 => '009_create_companies',
        8 => '010_create_courses',
        9 => '011_create_customers',
        10 => '012_create_document_company',
        11 => '013_create_events',
        12 => '014_create_files',
        13 => '015_create_inquiries',
        14 => '016_create_kuchikomi',
        15 => '017_create_member_regist',
        16 => '018_create_needs',
        17 => '019_create_pages',
        18 => '020_create_payments',
        19 => '021_create_privacies',
        20 => '022_create_profiles',
        21 => '023_create_projects',
        22 => '024_create_sections',
        23 => '025_create_tsubuyaki',
        24 => '027_create_users_clients',
        25 => '028_create_users_providers',
        26 => '029_create_users_scopes',
        27 => '030_create_users_sessions',
        28 => '031_create_users_sessionscopes',
        29 => '032_add_creditch_to_events',
        30 => '033_create_news',
        31 => '034_add_name_to_profiles',
        32 => '035_add_name_kana_to_profiles',
        33 => '036_create_application_credit_payments',
        34 => '037_add_name_to_applications',
        35 => '038_add_email_to_applications',
        36 => '039_add_amount_to_applications',
        37 => '040_add_payment_method_to_applications',
        38 => '041_add_incur_cancellation_fee_date_to_events',
        39 => '042_add_place_url_to_events',
        40 => '043_rename_field_token_to_charge_id_in_application_credit_payments',
        41 => '044_create_user_credit_cards',
        42 => '045_create_users_reminders',
        43 => '046_add_catchcopy_to_profiles',
        44 => '047_add_introduction_to_profiles',
        45 => '048_create_index_username_in_users',
        46 => '049_create_index_code_in_applications',
        47 => '050_create_index_application_code_in_application_credit_payments',
        48 => '051_create_index_code_in_events',
        49 => '052_create_index_code_in_member_regist',
        50 => '054_create_index_code_in_profiles',
        51 => '055_create_index_email_in_users',
        52 => '056_add_id_name_to_member_regist',
        53 => '057_add_industry_to_member_regist',
        54 => '058_add_industry_other_to_member_regist',
        55 => '059_delete_email_from_profiles',
        56 => '060_create_regist_reminders',
        57 => '061_create_application_cancels',
        58 => '062_add_email_to_regist_reminders',
        59 => '063_change_title_to_null_in_inquiries',
        60 => '064_create_application_credit_payment_sales',
        61 => '065_create_application_credit_payment_cancels',
        62 => '066_add_cancel_to_application_credit_payments',
        63 => '067_add_sale_to_application_credit_payments',
        64 => '068_add_secret_to_events',
        65 => '069_create_event_remind_mail_templates',
        66 => '070_create_event_remind_mails',
        67 => '071_create_event_remind_mail_default_templates',
        68 => '072_create_event_places',
        69 => '073_add_place_code_to_events',
        70 => '074_create_event_mails',
        71 => '075_create_event_other_dates',
        72 => '076_add_secret_to_blogs',
        73 => '077_add_display_to_events',
        74 => '078_add_display_event_date_to_events',
        75 => '079_create_event_display_top_pages',
      ),
    ),
    'module' => 
    array(
    ),
    'package' => 
    array(
      'auth' => 
      array(
        0 => '011_auth_group_optional',
      ),
    ),
  ),
  'folder' => 'migrations/',
  'table' => 'migration',
  'flush_cache' => false,
);
