<?php
namespace Fuel\Tasks;

use \Model\Base;

class Import_prev_event_applications {
    public static function run() {
        $list = self::get_data();

        $db = \Database_Connection::instance();
        $db->start_transaction();
        try {

            foreach($list as $value) {
                $username   = $value['username'];
                $event_code = $value['event_code'];

                $sql = 'SELECT * FROM member_regist WHERE username = "' . $username . '"';
                $user = \DB::query($sql)->execute()->current();

                $sql = 'SELECT * FROM events WHERE code = "' . $event_code . '"';
                $event = \DB::query($sql)->execute();
                if($user) {
                    $code = Base::getNewCode('applications');
                    $sql = 'INSERT INTO applications (code, event_code, username, name, email, cancel, amount, payment_method, disable, created_at) VALUE ("'. $code .'", "'. $event_code .'", "' . $username . '", "' . $user['name'] . '", "' . $user['email'] . '", 0, "' . $event['fee'] .', ", 3, 0, "' . $event['created_at'] . '");';
                    var_dump($sql);
                    \DB::query($sql)->execute()->current();
                }
            }
            $db->commit_transaction();

            return true;
        } catch (\Exception $e) {
            $db->rollback_transaction();
            echo $e;
            throw $e;
        }
    }

    private static function get_data() {
        return array(
            array('username' => 'gqkYeE7LH1Cp9lBD', 'event_code' => '3htC4k'),
            array('username' => 'EIhSo7qEa6W1Efeg', 'event_code' => '3htC4k'),
            array('username' => 'ULCv3rnRdH2N4LDs', 'event_code' => '3htC4k'),
            array('username' => 'nerFPVbRUXEryoGt', 'event_code' => '3htC4k'),
            array('username' => 'DYpoknYYa3NslLtI', 'event_code' => '3htC4k'),
            array('username' => 'NDMYv98WXN2YpLbV', 'event_code' => '3htC4k'),
            array('username' => 'CuaS2v4LEXxKDZ6z', 'event_code' => '3htC4k'),
            array('username' => 'ST9hfb0YCQatcIqx', 'event_code' => '3htC4k'),
            array('username' => 'ST9hfb0YCQatcIqx', 'event_code' => '3htC4k'),
            array('username' => 'MuNQNy4eBrGbdOZA', 'event_code' => '3htC4k'),
            array('username' => 'syPTemrGHarDY9SQ', 'event_code' => '3htC4k'),
            array('username' => 'iZQl87PoPGvuJYhf', 'event_code' => '5RGUmc'),
            array('username' => 'gqkYeE7LH1Cp9lBD', 'event_code' => '5RGUmc'),
            array('username' => '8WRL31NDz2c3sxkh', 'event_code' => '5RGUmc'),
            array('username' => 'Mvvaf3pVAOL62MDL', 'event_code' => '5RGUmc'),
            array('username' => 'JMRKdf1LuOpHGyM16', 'event_code' => '5RGUmc'),
            array('username' => '64TvUJwAR9ZVClvb', 'event_code' => '5RGUmc'),
            array('username' => '14UIVicEM5KnBQa1', 'event_code' => '5RGUmc'),
            array('username' => 'cI5q3Tr2mspDazff', 'event_code' => '5RGUmc'),
            array('username' => '0Jp45uUIgDrsIic4', 'event_code' => '5RGUmc'),
            array('username' => '4Ly9l8YGRWqL5hx9', 'event_code' => '5RGUmc'),
            array('username' => 'MuNQNy4eBrGbdOZA', 'event_code' => '5RGUmc'),
            array('username' => 'gqkYeE7LH1Cp9lBD', 'event_code' => '6L0m03'),
            array('username' => 'Abiu5bFHleNQscGV', 'event_code' => '6L0m04'),
            array('username' => '68sX7uUhGOx8skmE', 'event_code' => '6L0m05'),
            array('username' => 'J4G5sPh6bTcpdVzn', 'event_code' => '6L0m06'),
            array('username' => 'Kjo9vFlvef4dyolU', 'event_code' => '6L0m07'),
            array('username' => '4Ly9l8YGRWqL5hx11', 'event_code' => '8i6uc4'),
            array('username' => 'gqkYeE7LH1Cp9lBD', 'event_code' => 'D5CGNd'),
            array('username' => '8WRL31NDz2c3sxkh', 'event_code' => 'D5CGNd'),
            array('username' => 'JMRKdf1LuOpHGyM17', 'event_code' => 'D5CGNd'),
            array('username' => '41zESb0Vz58ixthD', 'event_code' => 'D5CGNd'),
            array('username' => 'cI5q3Tr2mspDazff', 'event_code' => 'D5CGNd'),
            array('username' => 'ST9hfb0YCQatcIqx', 'event_code' => 'D5CGNd'),
            array('username' => '0Jp45uUIgDrsIic3', 'event_code' => 'D5CGNd'),
            array('username' => '0Jp45uUIgDrsIic6', 'event_code' => 'D5CGNd'),
            array('username' => 'aEUqok24aP20GgTs', 'event_code' => 'D5CGNd'),
            array('username' => 'ST9hfb0YCQatcIqx', 'event_code' => 'drXSth'),
            array('username' => 'syPTemrGHarDY9SQ', 'event_code' => 'Emg6N4'),
            array('username' => 'cygfQi42Nmqxh7Dj', 'event_code' => 'Emg6N5'),
            array('username' => 'cygfQi42Nmqxh7Dj', 'event_code' => 'Emg6N6'),
            array('username' => 'Jh7bkw0TCqe5zAKa', 'event_code' => 'Emg6N7'),
            array('username' => 'QuXFL2iQLcB8KuT2', 'event_code' => 'EUkmQ2'),
            array('username' => '64TvUJwAR9ZVClvb', 'event_code' => 'EUkmQ3'),
            array('username' => 'IHTr9GwFlpQTP2sN', 'event_code' => 'EUkmQ4'),
            array('username' => 'J7wYELIDsBfO9dZ9', 'event_code' => 'EUkmQ5'),
            array('username' => 'a3hTL739aqT6LI13', 'event_code' => 'fLKaa4'),
            array('username' => 'DCm4adc9US3T0QkY', 'event_code' => 'fLKaa4'),
            array('username' => '68sX7uUhGOx8skmE', 'event_code' => 'fLKaa4'),
            array('username' => '68sX7uUhGOx8skmE', 'event_code' => 'fLKaa4'),
            array('username' => 'SKIuOqz8s7BQqxIX', 'event_code' => 'fLKaa4'),
            array('username' => 'TyprQ968VHj0uNUg', 'event_code' => 'fLKaa4'),
            array('username' => 'btfgJRpwcNk6G4E9', 'event_code' => 'FoVFLK'),
            array('username' => 'EIhSo7qEa6W1Efeg', 'event_code' => 'FoVFLK'),
            array('username' => '5tbuGnfymOZETzSB', 'event_code' => 'FoVFLK'),
            array('username' => 'JSTcqMmk20Tu6mNR', 'event_code' => 'FoVFLK'),
            array('username' => 'Kjo9vFlvef4dyolU', 'event_code' => 'FoVFLK'),
            array('username' => 'AxxjSxBtnbORniLJ', 'event_code' => 'FoVFLK'),
            array('username' => '0k5ULuSqeGQVuvxE', 'event_code' => 'jeOsl10'),
            array('username' => 'uMUECXDBHiURg3p0', 'event_code' => 'jeOsl11'),
            array('username' => 'qaCuO153VW8E04m9', 'event_code' => 'jeOsl12'),
            array('username' => 'JMRKdf1LuOpHGyM12', 'event_code' => 'jeOsl13'),
            array('username' => 'ASse3fxkVhUrvS0W', 'event_code' => 'jeOsl14'),
            array('username' => 'Z9pkPUIFx9oBotMu', 'event_code' => 'jeOsl15'),
            array('username' => '68sX7uUhGOx8skmE', 'event_code' => 'jeOsl16'),
            array('username' => 'wZnf2zu0AuBHcfj6', 'event_code' => 'jeOsl17'),
            array('username' => 'QuXFL2iQLcB8KuT1', 'event_code' => 'jeOsl18'),
            array('username' => 'WVN4Y29QE0MKHavn', 'event_code' => 'jeOsl19'),
            array('username' => 'J4G5sPh6bTcpdVzn', 'event_code' => 'jeOsl20'),
            array('username' => 'nerFPVbRUXEryoGt', 'event_code' => 'jeOsl21'),
            array('username' => 'nerFPVbRUXEryoGt', 'event_code' => 'jeOsl22'),
            array('username' => 'nerFPVbRUXEryoGt', 'event_code' => 'jeOsl23'),
            array('username' => 'DYpoknYYa3NslLtI', 'event_code' => 'jeOsl24'),
            array('username' => '64TvUJwAR9ZVClvb', 'event_code' => 'jeOsl25'),
            array('username' => '8yZHXGdPZIExcX7R', 'event_code' => 'jeOsl26'),
            array('username' => 'NDMYv98WXN2YpLbV', 'event_code' => 'jeOsl27'),
            array('username' => 'Pa7RJBu3Y6TEXsuG', 'event_code' => 'jeOsl28'),
            array('username' => '41zESb0Vz58ixthD', 'event_code' => 'jeOsl29'),
            array('username' => 'UNbsdQ6W5pvHI6kC', 'event_code' => 'jeOsl3'),
            array('username' => 'afLndckRHszm9TIc', 'event_code' => 'jeOsl30'),
            array('username' => 'OIMkOVc05cKo0T3a', 'event_code' => 'jeOsl31'),
            array('username' => 'ni78jVh9g03XRm6h', 'event_code' => 'jeOsl32'),
            array('username' => 'XaO6fjDGcNFKsdlH', 'event_code' => 'jeOsl33'),
            array('username' => 'gqkYeE7LH1Cp9lBD', 'event_code' => 'jeOsl4'),
            array('username' => 'EHnqgcCzYpW9HFEj', 'event_code' => 'jeOsl5'),
            array('username' => 'K17ahWglXQA6wAbh', 'event_code' => 'jeOsl6'),
            array('username' => 'EIhSo7qEa6W1Efeg', 'event_code' => 'jeOsl7'),
            array('username' => 'WmQvj8ji9PQy8rG1', 'event_code' => 'jeOsl8'),
            array('username' => '0ZzxPQS8PgP4yNz5', 'event_code' => 'jeOsl9'),
            array('username' => 'Ao2qM2Z4Jdn7kaVT', 'event_code' => 'kA8wTn'),
            array('username' => 'ULCv3rnRdH2N4LDs', 'event_code' => 'kA8wTn'),
            array('username' => '0Jp45uUIgDrsIic5', 'event_code' => 'kA8wTn'),
            array('username' => 'UNbsdQ6W5pvHI6kC', 'event_code' => 'KSXysn'),
            array('username' => 'JMRKdf1LuOpHGyM11', 'event_code' => 'KSXysn'),
            array('username' => 'Z9pkPUIFx9oBotMu', 'event_code' => 'KSXysn'),
            array('username' => 'SKIuOqz8s7BQqxIX', 'event_code' => 'KSXysn'),
            array('username' => '64TvUJwAR9ZVClvb', 'event_code' => 'KSXysn'),
            array('username' => 'SGU2K5PYM6CrVv93', 'event_code' => 'KSXysn'),
            array('username' => 'gqkYeE7LH1Cp9lBD', 'event_code' => 'l9nADX'),
            array('username' => 'ASse3fxkVhUrvS0W', 'event_code' => 'l9nADX'),
            array('username' => '8yZHXGdPZIExcX7R', 'event_code' => 'l9nADX'),
            array('username' => 'Pa7RJBu3Y6TEXsuG', 'event_code' => 'l9nADX'),
            array('username' => 'IHTr9GwFlpQTP2sN', 'event_code' => 'l9nADX'),
            array('username' => 'JMRKdf1LuOpHGyM10', 'event_code' => 'lUGZsI'),
            array('username' => 'JSTcqMmk20Tu6mNR', 'event_code' => 'lUGZsI'),
            array('username' => 'Kjo9vFlvef4dyolU', 'event_code' => 'lUGZsI'),
            array('username' => '64TvUJwAR9ZVClvb', 'event_code' => 'lUGZsI'),
            array('username' => '0Jp45uUIgDrsIic2', 'event_code' => 'n1EqEN'),
            array('username' => 'fw76r1WlXOC5Gb70', 'event_code' => 'n1EqEN'),
            array('username' => 'UNbsdQ6W5pvHI6kC', 'event_code' => 'oLLJoU'),
            array('username' => 'cI5q3Tr2mspDazff', 'event_code' => 'oLLJoU'),
            array('username' => 'ST9hfb0YCQatcIqx', 'event_code' => 'oLLJoU'),
            array('username' => '0Jp45uUIgDrsIic0', 'event_code' => 'oLLJoU'),
            array('username' => 'nerFPVbRUXEryoGt', 'event_code' => 'qPcn6a'),
            array('username' => 'RXErrQo8cPPiA46k', 'event_code' => 'qPcn6a'),
            array('username' => 'ST9hfb0YCQatcIqx', 'event_code' => 'QzZrka'),
            array('username' => 'DCm4adc9US3T0QkY', 'event_code' => 'sI3y5I'),
            array('username' => 'nerFPVbRUXEryoGt', 'event_code' => 'sI3y5I'),
            array('username' => '64TvUJwAR9ZVClvb', 'event_code' => 'sI3y5I'),
            array('username' => 'cI5q3Tr2mspDazff', 'event_code' => 'sI3y5I'),
            array('username' => 'gqkYeE7LH1Cp9lBD', 'event_code' => 'ToHJPK'),
            array('username' => 'EIhSo7qEa6W1Efeg', 'event_code' => 'ToHJPK'),
            array('username' => 'a3hTL739aqT6LI16', 'event_code' => 'ToHJPK'),
            array('username' => '0ZzxPQS8PgP4yNz4', 'event_code' => 'ToHJPK'),
            array('username' => '8WRL31NDz2c3sxkh', 'event_code' => 'ToHJPK'),
            array('username' => 'Mvvaf3pVAOL62MDL', 'event_code' => 'ToHJPK'),
            array('username' => 'qaCuO153VW8E04m8', 'event_code' => 'ToHJPK'),
            array('username' => 'JMRKdf1LuOpHGyM15', 'event_code' => 'ToHJPK'),
            array('username' => 'ASse3fxkVhUrvS0W', 'event_code' => 'ToHJPK'),
            array('username' => 'ASse3fxkVhUrvS0W', 'event_code' => 'ToHJPK'),
            array('username' => 'SnCLJl7oTygKVZBE', 'event_code' => 'ToHJPK'),
            array('username' => 'DCm4adc9US3T0QkY', 'event_code' => 'ToHJPK'),
            array('username' => '68sX7uUhGOx8skmE', 'event_code' => 'ToHJPK'),
            array('username' => 'kA1DFADdeGniLAI9', 'event_code' => 'ToHJPK'),
            array('username' => 'ULCv3rnRdH2N4LDs', 'event_code' => 'ToHJPK'),
            array('username' => 'SKIuOqz8s7BQqxIX', 'event_code' => 'ToHJPK'),
            array('username' => 'nerFPVbRUXEryoGt', 'event_code' => 'ToHJPK'),
            array('username' => 'DYpoknYYa3NslLtI', 'event_code' => 'ToHJPK'),
            array('username' => 'DYpoknYYa3NslLtI', 'event_code' => 'ToHJPK'),
            array('username' => '64TvUJwAR9ZVClvb', 'event_code' => 'ToHJPK'),
            array('username' => 'NDMYv98WXN2YpLbV', 'event_code' => 'ToHJPK'),
            array('username' => '41zESb0Vz58ixthD', 'event_code' => 'ToHJPK'),
            array('username' => 'cI5q3Tr2mspDazff', 'event_code' => 'ToHJPK'),
            array('username' => 'Ptml4luJf8dwbo7z', 'event_code' => 'ToHJPK'),
            array('username' => '4hlQJvqlD2x75Wh2', 'event_code' => 'ToHJPK'),
            array('username' => '4hlQJvqlD2x75Wh3', 'event_code' => 'ToHJPK'),
            array('username' => '0Jp45uUIgDrsIic1', 'event_code' => 'ToHJPK'),
            array('username' => 'J7wYELIDsBfO9dZ8', 'event_code' => 'ToHJPK'),
            array('username' => 'Pe0Ptqu9OIHouB6o', 'event_code' => 'ToHJPK'),
            array('username' => 'NzBFMqY2Qni2IHon', 'event_code' => 'ToHJPK'),
            array('username' => 'MnUmLVCfYArBGf1V', 'event_code' => 'ToHJPK'),
            array('username' => 'NsKYb8sPVajIaJkh', 'event_code' => 'ToHJPK'),
            array('username' => 'EVHqPaAFh73uHhap', 'event_code' => 'ToHJPK'),
            array('username' => 'A8rqr8zvThxqfHkr', 'event_code' => 'ToHJPK'),
            array('username' => 'MuNQNy4eBrGbdOZA', 'event_code' => 'ToHJPK'),
            array('username' => 'YpvGPmPoponTWpdP', 'event_code' => 'ToHJPK'),
            array('username' => 'yXFrQuSZDH80lYnw', 'event_code' => 'ToHJPK'),
            array('username' => 'EIhSo7qEa6W1Efeg', 'event_code' => 'umZiNF'),
            array('username' => 'ASse3fxkVhUrvS0W', 'event_code' => 'umZiNF'),
            array('username' => 'gqkYeE7LH1Cp9lBD', 'event_code' => 'uQ0bsm'),
            array('username' => 'DCm4adc9US3T0QkY', 'event_code' => 'uQ0bsm'),
            array('username' => '68sX7uUhGOx8skmE', 'event_code' => 'uQ0bsm'),
            array('username' => 'SKIuOqz8s7BQqxIX', 'event_code' => 'uQ0bsm'),
            array('username' => 'ST9hfb0YCQatcIqx', 'event_code' => 'uQ0bsm'),
            array('username' => 'A8rqr8zvThxqfHkr', 'event_code' => 'uQ0bsm'),
            array('username' => '8WRL31NDz2c3sxkh', 'event_code' => 'w0Y0OB'),
            array('username' => 'JMRKdf1LuOpHGyM18', 'event_code' => 'w0Y0OB'),
            array('username' => '2V71XTcJRn7n4rGn', 'event_code' => 'w0Y0OB'),
            array('username' => 'DYpoknYYa3NslLtI', 'event_code' => 'w0Y0OB'),
            array('username' => 'cygfQi42Nmqxh7Dj', 'event_code' => 'w0Y0OB'),
            array('username' => 'OBt1EAnLXwbU4gat', 'event_code' => 'w0Y0OB'),
            array('username' => 'gqkYeE7LH1Cp9lBD', 'event_code' => 'WBCu4s'),
            array('username' => 'IHTr9GwFlpQTP2sN', 'event_code' => 'WBCu4s'),
            array('username' => '7UbzHjnST0pCAcnk', 'event_code' => 'WBCu4s'),
            array('username' => 'RnedrAQakOlduLxK', 'event_code' => 'WBCu4s'),
            array('username' => '68sX7uUhGOx8skmE', 'event_code' => 'Xb3QJI'),
            array('username' => 'nerFPVbRUXEryoGt', 'event_code' => 'Xb3QJI'),
            array('username' => 'NDMYv98WXN2YpLbV', 'event_code' => 'Xb3QJI'),
            array('username' => 'afLndckRHszm9TIc', 'event_code' => 'Xb3QJI'),
            array('username' => '4hlQJvqlD2x75Wh1', 'event_code' => 'Xb3QJI'),
            array('username' => 'ASse3fxkVhUrvS0W', 'event_code' => 'xvZfeL'),
            array('username' => 'Pa7RJBu3Y6TEXsuG', 'event_code' => 'xvZfeL'),
            array('username' => 'u3NfXoFpGsr5eMGK', 'event_code' => 'xvZfeL'),
            array('username' => 'UbFM1frpqDGHqoaP', 'event_code' => 'xYnsYo'),
            array('username' => '8WRL31NDz2c3sxkh', 'event_code' => 'xYnsYo'),
            array('username' => 'cygfQi42Nmqxh7Dj', 'event_code' => 'xYnsYo'),
            array('username' => 'n1ON5cS8QlSCUIZC', 'event_code' => 'xYnsYo'),
            array('username' => 'rJdclZvbXh8it3cs', 'event_code' => 'xYnsYo'),
            array('username' => 'rfJVpt52vE3GLdvS', 'event_code' => 'xYnsYo'),
            array('username' => 'vU4UC6LxHzArCxht', 'event_code' => 'YfiUoX'),
            array('username' => 'UNbsdQ6W5pvHI6kC', 'event_code' => 'z2sQov'),
            array('username' => 'btfgJRpwcNk6G4E7', 'event_code' => 'z2sQov'),
            array('username' => 'JMRKdf1LuOpHGyM8', 'event_code' => 'z2sQov'),
            array('username' => '68sX7uUhGOx8skmE', 'event_code' => 'z2sQov'),
            array('username' => '9Ja3fCpVRZ9j7awa', 'event_code' => 'z2sQov'),
            array('username' => 'irUNVcUzMJanx8rp', 'event_code' => 'CPpAJy'),
            array('username' => '8K4QC71cnjsGEnBJ', 'event_code' => 'CPpAJy'),
            array('username' => 'gHepcQ8Lok8XvY45', 'event_code' => 'CPpAJy'),
            array('username' => 'iZQl87PoPGvuJYhf', 'event_code' => 'CPpAJy'),
            array('username' => 'gqkYeE7LH1Cp9lBD', 'event_code' => 'CPpAJy'),
            array('username' => 'EHnqgcCzYpW9HFEj', 'event_code' => 'CPpAJy'),
            array('username' => 'DGBz6mBG6TkWVKCp', 'event_code' => 'CPpAJy'),
            array('username' => 'Bpz9GreMKJtciP2o', 'event_code' => 'CPpAJy'),
            array('username' => 'MuNQNy4eBrGbdOZA', 'event_code' => 'CPpAJy'),
            array('username' => 'a3hTL739aqT6LI12', 'event_code' => ''),
            array('username' => 'DrUuHItjVJlKzqMm', 'event_code' => '7d65Iu'),
            array('username' => '8WRL31NDz2c3sxkh', 'event_code' => '7d65Iu'),
            array('username' => 'JMRKdf1LuOpHGyM9', 'event_code' => '7d65Iu'),
            array('username' => 'ULCv3rnRdH2N4LDs', 'event_code' => '7d65Iu'),
            array('username' => 'SKIuOqz8s7BQqxIX', 'event_code' => '7d65Iu'),
            array('username' => '4Ly9l8YGRWqL5hx10', 'event_code' => '7d65Iu'),
            array('username' => 'UNbsdQ6W5pvHI6kC', 'event_code' => 'vaADrM'),
            array('username' => 'a3hTL739aqT6LI14', 'event_code' => 'nMZEGf'),
            array('username' => 'A8rqr8zvThxqfHkr', 'event_code' => '9dlbLt'),
            array('username' => 'btfgJRpwcNk6G4E8', 'event_code' => 'VYDTpY'),
            array('username' => 'DrUuHItjVJlKzqMm', 'event_code' => 'VYDTpY'),
            array('username' => 'qaCuO153VW8E04m5', 'event_code' => 'VYDTpY'),
            array('username' => 'afLndckRHszm9TIc', 'event_code' => 'VYDTpY'),
            array('username' => 'CuaS2v4LEXxKDZ6z', 'event_code' => 'VYDTpY'),
            array('username' => '8WRL31NDz2c3sxkh', 'event_code' => 'vYKs6K'),
            array('username' => 'qaCuO153VW8E04m6', 'event_code' => 'vYKs6K'),
            array('username' => 'Ao2qM2Z4Jdn7kaVT', 'event_code' => 'vYKs6K'),
            array('username' => 'ULCv3rnRdH2N4LDs', 'event_code' => 'vYKs6K'),
            array('username' => 'u3NfXoFpGsr5eMGK', 'event_code' => 'vYKs6K'),
            array('username' => 'cNDym9HulURWgTR8', 'event_code' => 'vYKs6K'),
            array('username' => 'MuNQNy4eBrGbdOZA', 'event_code' => 'vYKs6K'),
            array('username' => 'DIqs65YxGiJFh4b2', 'event_code' => 'vYKs6K'),
            array('username' => 'kQaG54enkifqx1ly', 'event_code' => 'vYKs6K'),
            array('username' => 'EIhSo7qEa6W1Efeg', 'event_code' => 'AhroTm'),
            array('username' => '0ZzxPQS8PgP4yNz2', 'event_code' => 'AhroTm'),
            array('username' => '8WRL31NDz2c3sxkh', 'event_code' => 'AhroTm'),
            array('username' => 'JMRKdf1LuOpHGyM14', 'event_code' => 'AhroTm'),
            array('username' => 'ASse3fxkVhUrvS0W', 'event_code' => 'AhroTm'),
            array('username' => 'SKIuOqz8s7BQqxIX', 'event_code' => 'AhroTm'),
            array('username' => 'cI5q3Tr2mspDazff', 'event_code' => 'AhroTm'),
            array('username' => 'NzBFMqY2Qni2IHon', 'event_code' => 'AhroTm'),
            array('username' => 'EeOrt8IbGEDjbh6U', 'event_code' => 'AhroTm'),
            array('username' => 'v8mktsdDDV6UpjFv', 'event_code' => 'drXSth'),
            array('username' => 'zs67ac4kMxwUJpV3', 'event_code' => 'drXSth'),
            array('username' => 'Ud4JOdTjMeTORV2E', 'event_code' => 'drXSth'),
            array('username' => '7Z3baGgPzNU30npQ', 'event_code' => 'drXSth'),
            array('username' => 'SGU2K5PYM6CrVv92', 'event_code' => 'drXSth'),
            array('username' => '4hlQJvqlD2x75Wh0', 'event_code' => '3paEXm'),
            array('username' => 'nerFPVbRUXEryoGt', 'event_code' => 'NqdeBV'),
            array('username' => '14UIVicEM5KnBQa0', 'event_code' => 'NqdeBV'),
            array('username' => '68sX7uUhGOx8skmE', 'event_code' => 'NqdeBV'),
            array('username' => 'NH9OJkrw1e5DgDYF', 'event_code' => 'A5TP2p'),
            array('username' => 'JMRKdf1LuOpHGyM13', 'event_code' => 'NqdeBV'),
            array('username' => '8WRL31NDz2c3sxkh', 'event_code' => 'NqdeBV'),
            array('username' => 'UNbsdQ6W5pvHI6kC', 'event_code' => 'sGNvls'),
            array('username' => 'btfgJRpwcNk6G4E6', 'event_code' => 'TZgbC1'),
            array('username' => 'EIhSo7qEa6W1Efeg', 'event_code' => 'TZgbC1'),
            array('username' => 'EIhSo7qEa6W1Efeg', 'event_code' => 'sGNvls'),
            array('username' => 'isv8XyJveIkH9d9v', 'event_code' => 'TZgbC1'),
            array('username' => 'a3hTL739aqT6LI17', 'event_code' => 'TZgbC1'),
            array('username' => 'DrUuHItjVJlKzqMm', 'event_code' => 'sGNvls'),
            array('username' => 'DrUuHItjVJlKzqMm', 'event_code' => 'TZgbC1'),
            array('username' => 'IlIteazX42CIwCYO', 'event_code' => 'TZgbC1'),
            array('username' => 'rQZU3WCQqBTjgKVh', 'event_code' => 'A5TP2p'),
            array('username' => 'qaCuO153VW8E04m4', 'event_code' => 'TZgbC1'),
            array('username' => 'hCd4RhMEZKS0uQWV', 'event_code' => 'TZgbC1'),
            array('username' => 'JMRKdf1LuOpHGyM19', 'event_code' => 'TZgbC1'),
            array('username' => 'DCm4adc9US3T0QkY', 'event_code' => 'A5TP2p'),
            array('username' => 'MuNQNy4eBrGbdOZA', 'event_code' => 'TZgbC1'),
            array('username' => 'a3hTL739aqT6LI15', 'event_code' => '9dlbLt'),
            array('username' => '8WRL31NDz2c3sxkh', 'event_code' => '9dlbLt'),
            array('username' => 'qaCuO153VW8E04m7', 'event_code' => '9dlbLt'),
            array('username' => 'ASse3fxkVhUrvS0W', 'event_code' => '9dlbLt'),
            array('username' => 'ASse3fxkVhUrvS0W', 'event_code' => '9dlbLt'),
            array('username' => 'Z9pkPUIFx9oBotMu', 'event_code' => '9dlbLt'),
            array('username' => 'WLeJqeEGORixCNcb', 'event_code' => '9dlbLt'),
            array('username' => 'Ao2qM2Z4Jdn7kaVT', 'event_code' => '9dlbLt'),
            array('username' => 'anIc1RuYhN4IHuDt', 'event_code' => '9dlbLt'),
            array('username' => '68sX7uUhGOx8skmE', 'event_code' => '9dlbLt'),
            array('username' => 'kA1DFADdeGniLAI8', 'event_code' => '9dlbLt'),
            array('username' => 'ULCv3rnRdH2N4LDs', 'event_code' => '9dlbLt'),
            array('username' => 'SKIuOqz8s7BQqxIX', 'event_code' => '9dlbLt'),
            array('username' => 'bplrmOZyJW9uvQmy', 'event_code' => '9dlbLt'),
            array('username' => 'DYpoknYYa3NslLtI', 'event_code' => '9dlbLt'),
            array('username' => '64TvUJwAR9ZVClvb', 'event_code' => '9dlbLt'),
            array('username' => 'NDMYv98WXN2YpLbV', 'event_code' => '9dlbLt'),
            array('username' => 'cI5q3Tr2mspDazff', 'event_code' => '9dlbLt'),
            array('username' => 'cI5q3Tr2mspDazff', 'event_code' => '9dlbLt'),
            array('username' => 'ST9hfb0YCQatcIqx', 'event_code' => '9dlbLt'),
            array('username' => 'XsAXbrl1Th6u7OUA', 'event_code' => '9dlbLt'),
            array('username' => '0Jp45uUIgDrsIic7', 'event_code' => '9dlbLt'),
            array('username' => 'Pe0Ptqu9OIHouB6o', 'event_code' => '9dlbLt'),
            array('username' => 'pOHz5gSDbWlLmk8v', 'event_code' => '9dlbLt'),
            array('username' => 'MuNQNy4eBrGbdOZA', 'event_code' => '9dlbLt'),
            array('username' => 'cygfQi42Nmqxh7Dj', 'event_code' => '9dlbLt'),
            array('username' => 'qhZZ4ALobDmTsGcs', 'event_code' => '9dlbLt'),
            array('username' => 'kQaG54enkifqx1ly', 'event_code' => '9dlbLt'),
            array('username' => '0ZzxPQS8PgP4yNz3', 'event_code' => '9dlbLt'),
        );
    }
}

