name: PR notify

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: pull-request notify
        env:
          ROOM_ID: '176039022'
          REPO_NAME: 'kinyu-joshi.jp'
          BODY: 'プルリクエストが作成されました'
        run: |
          git log --pretty=short -1 > gitlog.txt
          curl -s -X POST -H "X-ChatWorkToken: ${{secrets.CHATWORK_API_TOKEN}}" -d "body=[info][title]${REPO_NAME}[/title]`cat gitlog.txt`[/info]" "https://api.chatwork.com/v2/rooms/${ROOM_ID}/messages"

